#!/bin/bash
function pullRequest() {
    echo Enter pull request title
    read TITLE
    echo Enter pull request body
    read BODY
    USERNAME=$(git config user.name)
    HEAD=$(git name-rev --name-only HEAD)
    BASE=$(git name-rev --name-only MASTER)
    MID=$(git remote -v | grep -m 1 "(push)" | sed -e "s/.*github.com[:/]\(.*\)\.git.*/\1/")
    BEG="https://api.github.com/repos/"
    END="/pulls"
    URL=$BEG$MID$END
    NOWHITE="$(echo -e "${URL}" | tr -d '[[:space:]]')"
    echo $NOWHITE
    curl -i -u "$USERNAME" -H "Content-Type: application/json" -X POST -d '{"title": "'"$TITLE"'", "body": "'"$BODY"'", "head": "'"$HEAD"'", "base": "'"$BASE"'"}' $NOWHITE
}

export -f pullRequest
